spring:
  jpa:
    database:MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/hzyh
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

profile:
  type: dev
